user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;
    server_tokens off;

    gzip on;
    gzip_comp_level 5;
    gzip_min_length 1024;
    gzip_types text/plain text/css application/json application/javascript image/svg+xml;

    server {
        listen 80;
        server_name _;

        root /acg-faka;
        index index.php index.html;

        client_max_body_size 50m;

        location / {
            if (!-e $request_filename) {
                rewrite ^(.*)$ /index.php?s=$1 last;
                break;
            }
        }

        location ~ \.php$ {
            try_files $uri =404;

            include fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        location ~* \.(css|js|woff|woff2|ttf|eot)$ {
            expires 7d;
            add_header Cache-Control "public";
        }

        location ~ /\.(?!well-known).* {
            deny all;
        }
    }
}
